# Site settings
title:          Projects
description:    "Babak Rafian project's portal"
baseurl:        "/projects"
url:            "https://babakrafian.github.io"

# Author
author:
  name:         Babak Rafian
  url:          https://babakrafian.github.io
  email:        babak.rafian@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

theme:      tale
# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
